version: "3.8"
services:
  userservice:
    container_name: userservise
    image: userservice
    restart: always
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    env_file:
      - ./.env
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
